import { chromium } from 'playwright';
import fs from 'node:fs';
const OUT = 'docs/review-shots';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on('dialog', (d) => d.accept());
await page.goto('http://127.0.0.1:8765/process-planner.html');
await page.waitForFunction(() => !!window.planner, undefined, { timeout: 60_000 });
const g = JSON.parse(fs.readFileSync(`${OUT}/create_customer.export.json`, 'utf8'));
g.nodes.find((n) => n.id === 'data_1').expects[0].target = 'Account';
await page.evaluate((g) => window.planner.load(g), g);
await page.evaluate(() => refreshInsertMenu());
const vals = await page.locator('#f_insert option').evaluateAll((os) => os.map((o) => o.value));
console.log('insert options:', vals.join(' | '));
await page.selectOption('#f_insert', 'lib:expense_to_siebel');
await page.waitForTimeout(1000);
await page.click('#b_fit'); await page.waitForTimeout(300);
await page.screenshot({ path: `${OUT}/25-after-insert-island.png` });
console.log('status:', await page.locator('#status').innerText());
await page.click('#b_check'); await page.waitForTimeout(300);
await page.screenshot({ path: `${OUT}/26-check-after-insert.png` });
const iss = await page.evaluate(() => window.planner.issues());
console.log('issues after insert:', iss.errors.length, 'errors;', iss.gaps.map((x) => x.kind + '@' + x.at).join(', '));
// import cases dialog
await page.click('#b_cases'); await page.waitForTimeout(400);
await page.screenshot({ path: `${OUT}/27-import-cases.png` });
await browser.close();
